image:
  repository: ghcr.io/meffazm/ru-jailbreak-guard/predictor-tfidf
  tag: sha-5600fc7
  pullPolicy: IfNotPresent
modelVersion: "1"
mlflowTrackingUri: http://mlflow.mlflow.svc.cluster.local:5000
mlflowS3Endpoint: http://minio.minio.svc.cluster.local:9000
awsRegion: us-east-1
modelName: ru-jailbreak-tfidf-logreg
replicas:
  min: 1
  max: 3
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
