apiVersion: v2
name: postgres-app
version: 0.1.0
description: Single-pod Postgres for mlflow + flyte
dependencies:
  - name: postgresql
    version: 16.7.0
    repository: https://charts.bitnami.com/bitnami
