mlflow:
  global:
    security:
      allowInsecureImages: true
  tracking:
    enabled: true
    replicaCount: 1
    auth:
      enabled: false
    service:
      type: ClusterIP
      ports:
        http: 5000
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
  run:
    enabled: false
  postgresql:
    enabled: true
    auth:
      username: mlflow
      password: mlflow
      database: mlflow
    primary:
      persistence:
        size: 4Gi
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1
          memory: 1Gi
  minio:
    enabled: true
    auth:
      rootUser: minioadmin
      rootPassword: minioadmin
    defaultBuckets: "mlflow"
    persistence:
      size: 8Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 1Gi
